version: '3.7'
services:
  kafka:
    container_name: kafka
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    networks:
      - foas-net

  crowdnav:
    container_name: crowdnav
    build:
      context: ./crowdnav
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - foas-net
    volumes:
      - csvexchangevolume:/app/data/

networks:
  foas-net:
    name: foas-net
    driver: bridge

volumes:
  csvexchangevolume:
