version: '3.7'
services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - '2181:2181'
      - '9092:9092'
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    networks:
      - kafka

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
